using System.ComponentModel.DataAnnotations;

namespace webWarehouseInventoryManagement.Models
{
    public class ListingFormModel
    {
        public Guid idListingProduct { get; set; }
        public Guid idCountryOfOrigin { get; set; }

        [Required(ErrorMessage = "Please select a listing product")]
        public string ListingProduct { get; set; }

        [Required(ErrorMessage = "Please select a number of styles")]
        [Range(1, 15, ErrorMessage = "Select between 1 and 15 styles")]
        public int? NumberOfStyles { get; set; }

        [Required(ErrorMessage = "Please select a colour")]
        //public string Colour { get; set; }
        public List<string> Colour { get; set; } = new();

        [Required(ErrorMessage = "Please select a sizes")]
         //public List<string> Size { get; set; } = new List<string>();
         public string Size { get; set; }
        [Required(ErrorMessage = "Please select a adult sizes")]
        //public string AdultSize { get; set; }
        public List<string> AdultSize { get; set; } = new();
        [Required(ErrorMessage = "Please select a kids sizes")]
        //public string KidsSize { get; set; }
        public List<string> KidsSize { get; set; } = new();

        [Required(ErrorMessage = "Please enter the category name")]
        [StringLength(100)]
        public string CategoryName { get; set; }

        [Required(ErrorMessage = "Please select a style name option")]
        public string StyleNameOption { get; set; }  // None or New

        [Required(ErrorMessage = "Please enter the style name")]
        public List<string> StyleNames { get; set; } = new List<string>();

        [Required(ErrorMessage = "Please select a price change option")]
        public string PriceChange { get; set; }  // Yes or No

        [Required(ErrorMessage = "Please enter the adult price")]
        public decimal? AdultPrice { get; set; }
        [Required(ErrorMessage = "Please enter the kids price")]
        public decimal? KidsPrice { get; set; }

        [Required(ErrorMessage = "Please select a country of origin")]
        public string CountryOfOrigin { get; set; }
        public string CountryName { get; set; }

        [Required(ErrorMessage = "Please enter the title")]
        [StringLength(200)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please enter the bullet points")]
        public string BulletPoints { get; set; }

        [Required(ErrorMessage = "Please enter the description")]
        public string Description { get; set; }

        //[Required(ErrorMessage = "Please enter the search terms")]
        public string? SearchTerms { get; set; }

        [Required(ErrorMessage = "Please select design type")]
        public string DesignType { get; set; } = "DTF Stock";

        [Required(ErrorMessage = "Please enter the bullet point 1")]
        public string Bp1 { get; set; }
        [Required(ErrorMessage = "Please enter the bullet point 2")]
        public string Bp2 { get; set; }
        [Required(ErrorMessage = "Please enter the bullet point 3")]
        public string Bp3 { get; set; }
        [Required(ErrorMessage = "Please enter the bullet point 4")]
        public string Bp4 { get; set; }
        [Required(ErrorMessage = "Please enter the bullet point 5")]
        public string Bp5 { get; set; }

        [Required(ErrorMessage = "Please enter the product cost")]
        public decimal? ProductCost { get; set; }

        public List<StyleImage> StyleImages { get; set; } = new();

        public List<ColorModel> Colors { get; set; }
        public List<CountryModel> Countrys { get; set; }
        public List<DesignTypeModel> DesignTypes { get; set; }

        public List<SizeCategoryModel> SizeCategories { get; set; }
        public List<SizeModel> Sizes { get; set; }
        public List<StyleModel> Styles { get; set; } = new();
        public List<string> AutoGeneratedStyles { get; set; } = new();
        public List<string> CustomStyles { get; set; } = new(); // if "New"
        public List<string> FinalStyleNames { get; set; } = new(); // if "New"
        public string ParentSKU { get; set; }
        public List<ChildSKUInfo> ChildSKUs { get; set; }

        public string AdultBrowseNode { get; set; }
        public string KidsBrowseNode { get; set; }
        public string ProductName { get; set; }
        public string DateAdd { get; set; }
        public string UpdatedDate { get; set; }
        public string color { get; set; }

    }
    public class ChildSKUModel
    {
        public string SKU { get; set; }
        public string SizeName { get; set; }
        public string SizeMap { get; set; }
        public string Color { get; set; }
        public decimal Price { get; set; }
        public Guid ColorId { get; set; }
        //public int SizeId { get; set; }
        public string StyleId { get; set; }
        public string MainImageUrl { get; set; }
        public string OtherImageUrl { get; set; }
    }

    public class ChildSKUInfo
    {
        public string SKU { get; set; }
        public string Title { get; set; }
        public string StyleName { get; set; }
        public string Color { get; set; }
        public string ColorMap { get; set; }
        public string SizeName { get; set; }
        public string SizeMap { get; set; }
        public decimal SalePrice { get; set; }
        public string MainImageUrl { get; set; }
        public string OtherImageUrl { get; set; }
        public string ProductTextCode { get; set; }
        public string CountryOfOrigin { get; set; }

        public int StyleNo { get; set; }
        public Guid ColorId { get; set; }
        public string SizeCategory { get; set; }
    }
    public class StyleImage
    {
        //[Required(ErrorMessage = "Please enter the main image URL")]
        //public string MainImage { get; set; }

        public List<ColorImage> ColorImages { get; set; } = new();

        [Required(ErrorMessage = "Please enter the other image URL")]
        public string OtherImage { get; set; }
        public int StyleNo { get; set; }
        public string StyleName { get; set; }

    }
    public class ColorImage
    {
        [Required(ErrorMessage = "Please enter the main image URL")]
        public string MainImage { get; set; }
        public string OtherImage { get; set; }
        public string idColor { get; set; }   // optional, if you need to know which color
       
        public string ColorName { get; set; } // optional
    }
    public class ColorModel
    {
        [Required(ErrorMessage = "Please select a colour")]
        public Guid idColor { get; set; }
        public string Color { get; set; }
        public string ColorMap { get; set; }
    }

    public class CountryModel
    {
        [Required(ErrorMessage = "Please select a country of origin")]
        public Guid idCountryOfOrigin { get; set; }
        public string Country { get; set; }
    }

    public class DesignTypeModel
    {
        [Required(ErrorMessage = "Please select design type")]
        public Guid idListingDesignType { get; set; }
        public string DesignType { get; set; }
    }
    public class SizeCategoryModel
    {
        public int idSizeCategory { get; set; }
        public string SizeCategory { get; set; } // Adults, Kids

        public List<SizeModel> Sizes { get; set; } = new List<SizeModel>();
    }

    public class SizeModel
    {
        public int idSize { get; set; }
        public int idSizeCategory { get; set; }
        public string SizeName { get; set; } // X-Small, 1-2 Years, etc.
        public string SizeMap { get; set; }  // XS, 1-2Y, etc.
                                             // Add this to match your SQL query
        public string SizeCategory { get; set; }
    }

    public class StyleModel
    {
        public Guid idListingStyle { get; set; }
        public string StyleName { get; set; }
        public int StyleNo { get; set; }

        public List<StyleImage> Images { get; set; } = new();
    }

    // Add this class for the generated listing data
    public class AmazonSheetDefaults
    {
        public string FeedProductType { get; set; }
        public string BrandName { get; set; }
        public string LifecycleSupplyType { get; set; }
        public string ClosureType { get; set; }
        public string OuterMaterialType { get; set; }
        public string FabricType { get; set; }
        public string SupplierDeclaredMaterialRegulation { get; set; }
        public string TShirtStandardPrice { get; set; }
        public string SweatshirtStandardPrice { get; set; }
        public string HoodieStandardPrice { get; set; }
        public string Quantity { get; set; }
        public string KidsTargetGender { get; set; }
        public string KidsDepartmentName { get; set; }
        public string AdultsTargetGender { get; set; }
        public string AdultsDepartmentName { get; set; }
        public string Manufacturer { get; set; }
        public string CareInstructions { get; set; }
        public string VariationTheme { get; set; }
        public string UpdateDelete { get; set; }
        public string FitType { get; set; }
        public string ConditionType { get; set; }
        public string Currency { get; set; }
        public decimal UVPListPrice { get; set; }
    }

    public class SellerSKU
    {
        public string SKU { get; set; }
        public string ParentSKU { get; set; }
    }
    public class SettingsModel
    {
        public string ProductType { get; set; }   // Hoodie, T-shirt, Sweatshirt, etc.
        public string Category { get; set; }      // Kids / Adults
        public string BrowseNodes { get; set; }   // The node value
    }
    public class TemplateListModel
    {
        public Guid idListingProduct { get; set; }
        public string ProductType { get; set; }
        public string CategoryName { get; set; }      // Kids / Adults
        public string Title { get; set; }
        public string FolderPath { get; set; }
        public string DateAdd { get; set; }
        public string UpdatedDate { get; set; }
    }

    public class ListingImageDto
    {
        public Guid idListingStyle { get; set; }
        public Guid idColor { get; set; }
        public string Color { get; set; }
        public string MainImageUrl { get; set; }
        public string OtherImageUrl { get; set; }
    }
    public class ListingStyleDto
    {
        public Guid idListingStyle { get; set; }
        public int StyleNo { get; set; }
        public string StyleName { get; set; }
    }
}
